<a href="https://colab.research.google.com/github/DemetrioJMartins/aulas_faculdade_data_science/blob/main/Semana_2_Exerc%C3%ADcio_de_apoio_Introdu%C3%A7%C3%A3o_a_Ciencia_de_Dados_COM350.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Disciplina - Introdução a Ciência de Dados - Univesp
##Exercícios de Apoio da Semana 2

###1 - Carregue as bibliotecas NumPy e Pandas

In [ ]:
import pandas as pd
import numpy as np

###2 - Crie um NDArray com os seguintes valores [1, 2.5, 7, -78, -0.9, 130, 25]

In [ ]:
lista=[1, 2.5, 7, -78, -0.9, 130, 25]
dados=np.array(lista)

In [ ]:
dados

array([  1. ,   2.5,   7. , -78. ,  -0.9, 130. ,  25. ])

###3 - Crie um NDArray com os valores de 0 a 10

In [ ]:
dados2=np.arange(11)

In [ ]:
dados2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

 ###4 – Crie um NDArray de dimensão 2x5 com valores 1

In [ ]:
dados3=np.ones((2,5))
dados3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

###5 – Crie um NDArray com valores de 1 a 100, com intervalos de 3 em 3.

In [ ]:
dados4=np.arange(0,100,3)
dados4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

###6 – Mostre as raízes quadradas dos valores do NDArray criado no exercícios 5.

In [ ]:
np.sqrt(dados4)

array([0.        , 1.73205081, 2.44948974, 3.        , 3.46410162,
       3.87298335, 4.24264069, 4.58257569, 4.89897949, 5.19615242,
       5.47722558, 5.74456265, 6.        , 6.244998  , 6.4807407 ,
       6.70820393, 6.92820323, 7.14142843, 7.34846923, 7.54983444,
       7.74596669, 7.93725393, 8.1240384 , 8.30662386, 8.48528137,
       8.66025404, 8.83176087, 9.        , 9.16515139, 9.32737905,
       9.48683298, 9.64365076, 9.79795897, 9.94987437])

###7 – Altere a décima posição do NDArray criado no exercício 5 com o dobro do seu valor.

In [ ]:
dados4[9]=dados4[9]*2
dados4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 54, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

###8 – Execute o comando para criar um Dataframe com os dados disponíveis no notebook.

In [ ]:
dados={'Empresa':['Microsoft', 'Google','Univesp','NVData Analytics','Power Bi Experience','USP'], 'Qtde Func':[1000, 1500,500, 100,100,499], 'Site':['https://www.microsoft.com/pt-br','https://www.google.com/','https://univesp.br/','https://www.nvdata.com.br/','https://powerbiexperience.com/pt/','https://www.usp.br/'],'Instagram':['@microsoft','@google','@univespoficial','@nv_data','@leokarpa','@usp.oficial'],'Criação':[1975,1998,2012,2019,2016,1934], 'País':['EUA','EUA','Brasil','Brasil','Brasil','Brasil']}

In [ ]:
df1=pd.DataFrame(dados)
df1

Empresa  Qtde Func                               Site  \
0            Microsoft       1000    https://www.microsoft.com/pt-br   
1               Google       1500            https://www.google.com/   
2              Univesp        500                https://univesp.br/   
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

         Instagram  Criação    País  
0       @microsoft     1975     EUA  
1          @google     1998     EUA  
2  @univespoficial     2012  Brasil  
3         @nv_data     2019  Brasil  
4        @leokarpa     2016  Brasil  
5     @usp.oficial     1934  Brasil

###9 – Execute um comando que seja possível identificar qual a média da quantidade de funcionários que as empresas listadas tem. Informe também a soma dos funcionários que as empresas tem.


In [ ]:
df1['Qtde Func'].describe()

count       6.000000
mean      616.500000
std       545.631286
min       100.000000
25%       199.750000
50%       499.500000
75%       875.000000
max      1500.000000
Name: Qtde Func, dtype: float64

###10 – Mostre as primeiras 3 linhas do dataframe.

In [ ]:
df1.head(3)

Empresa  Qtde Func                             Site        Instagram  \
0  Microsoft       1000  https://www.microsoft.com/pt-br       @microsoft   
1     Google       1500          https://www.google.com/          @google   
2    Univesp        500              https://univesp.br/  @univespoficial   

   Criação    País  
0     1975     EUA  
1     1998     EUA  
2     2012  Brasil

###11 – Mostre as últimas 3 linhas do dataframe.

In [ ]:
df1.tail(3)

Empresa  Qtde Func                               Site  \
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

      Instagram  Criação    País  
3      @nv_data     2019  Brasil  
4     @leokarpa     2016  Brasil  
5  @usp.oficial     1934  Brasil

###12 – Liste apenas as linhas em que as empresas foram criadas nos últimos 10 anos. Informe a quantidade de registros.

In [ ]:
df1[df1['Criação']>=2013]

Empresa  Qtde Func                               Site  \
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   

   Instagram  Criação    País  
3   @nv_data     2019  Brasil  
4  @leokarpa     2016  Brasil

###13 – Vamos imaginar que em todas as empresas exista 1 chefe para cada 23 funcionários. Crie uma coluna que mostre a quantidade de chefes que cada empresa teria e depois informe quantos chefes teríamos ao todo. (os valores não precisam ser números inteiros, é apenas uma estimativa).


In [ ]:
df1['Chefes']=df1['Qtde Func']/23
df1

Empresa  Qtde Func                               Site  \
0            Microsoft       1000    https://www.microsoft.com/pt-br   
1               Google       1500            https://www.google.com/   
2              Univesp        500                https://univesp.br/   
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

         Instagram  Criação    País     Chefes  
0       @microsoft     1975     EUA  43.478261  
1          @google     1998     EUA  65.217391  
2  @univespoficial     2012  Brasil  21.739130  
3         @nv_data     2019  Brasil   4.347826  
4        @leokarpa     2016  Brasil   4.347826  
5     @usp.oficial     1934  Brasil  21.695652